config/routes.rb
Blogger::Application.routes.draw do
  get "articles/index"

  get "articles/show"

  get "articles/new"

  get "articles/create"

  get "articles/edit"

  get "articles/update"

  resources :articles
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
    render json: @articles
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(
        title: params[:article][:title],
        body: params[:article][:body])
    # @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    redirect_to article_path(@article)
  end
  def destroy
    Article.delete(params[:id])
    @articles = Article.all
    render "index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= form_for(@article) do |f| %>
    <ul>
      <% @article.errors.full_messages.each do |error| %>
          <li><%= error %></li>
      <% end %>
    </ul>
    <p>
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
      <li>
        <%= link_to article.title, article_path(article) %>
      </li>
  <% end %>
</ul>

<%= link_to "Create a New Article", new_article_path, class: "new_article" %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= form_for(@article) do |f| %>
    <ul>
      <% @article.errors.full_messages.each do |error| %>
          <li><%= error %></li>
      <% end %>
    </ul>
    <p>
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>

<%= link_to "delete", article_path(@article), method: :delete %>

<%= link_to "<< Back to Articles List", articles_path %>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>